version: 1
disable_existing_loggers: True
formatters:
  simple:
    format: "%(asctime)s - %(module)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: log/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: log/errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  models:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler]
    propagate: no

  resources:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler]
    propagate: no

  utils:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler]
    propagate: no

root:
  level: ERROR
  handlers: [console, info_file_handler, error_file_handler]
